**Operations for Tensors**

In [20]:
import torch

In [24]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [28]:
x = torch.rand(3,2)
print(x)

tensor([[0.3451, 0.6855],
        [0.1917, 0.6562],
        [0.2547, 0.1577]])


In [32]:
x = torch.ones(2,4, dtype=torch.int)
print(x.dtype)
print(x.size())

torch.int32
torch.Size([2, 4])


In [36]:
x = [1,2,3,4]
x = torch.tensor(x)
print(x)

tensor([1, 2, 3, 4])


In [70]:
y = [2,3,4,5]
z = x+torch.tensor(y)
print(z)
print(y)

tensor([3, 5, 7, 9])
[2, 3, 4, 5]


In [80]:
torch.add(z, torch.tensor(y))

tensor([ 5,  8, 11, 14])

In [82]:
torch.sub(z, x)

tensor([2, 3, 4, 5])

In [84]:
torch.mul(z, x)

tensor([ 3, 10, 21, 36])

In [86]:
torch.div(z, x)

tensor([3.0000, 2.5000, 2.3333, 2.2500])

In [76]:
a = torch.tensor(y)
print(a)
a.add_(z-x)

tensor([2, 3, 4, 5])


tensor([ 4,  6,  8, 10])

In [112]:
r = torch.rand(4,5)
print(r)
print(r[1,:])
print(r[2,0].item())
r.size()

tensor([[0.4827, 0.4343, 0.6226, 0.9058, 0.8467],
        [0.4860, 0.6312, 0.4844, 0.8436, 0.2603],
        [0.4836, 0.5202, 0.5219, 0.4857, 0.2247],
        [0.3705, 0.5056, 0.8963, 0.0279, 0.0667]])
tensor([0.4860, 0.6312, 0.4844, 0.8436, 0.2603])
0.4835948944091797


torch.Size([4, 5])

In [114]:
r = r.view(-1, 2)
print(r)
r.size()

tensor([[0.4827, 0.4343],
        [0.6226, 0.9058],
        [0.8467, 0.4860],
        [0.6312, 0.4844],
        [0.8436, 0.2603],
        [0.4836, 0.5202],
        [0.5219, 0.4857],
        [0.2247, 0.3705],
        [0.5056, 0.8963],
        [0.0279, 0.0667]])


torch.Size([10, 2])

**Conversion from Numpy array to Tensor and vice versa**

In [122]:
import numpy as np

In [124]:
a = torch.zeros(4)
print(a)
b = a.numpy()
print(b)
print(b.dtype)

tensor([0., 0., 0., 0.])
[0. 0. 0. 0.]
float32


In [126]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
