**Operations for Tensors**

In [8]:
import torch

In [9]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [10]:
x = torch.rand(3,2)
print(x)

tensor([[0.3633, 0.2588],
        [0.3116, 0.8289],
        [0.5019, 0.2329]])


In [11]:
x = torch.ones(2,4, dtype=torch.int)
print(x.dtype)
print(x.size())

torch.int32
torch.Size([2, 4])


In [12]:
x = [1,2,3,4]
x = torch.tensor(x)
print(x)

tensor([1, 2, 3, 4])


In [13]:
y = [2,3,4,5]
z = x+torch.tensor(y)
print(z)
print(y)

tensor([3, 5, 7, 9])
[2, 3, 4, 5]


In [14]:
torch.add(z, torch.tensor(y))

tensor([ 5,  8, 11, 14])

In [15]:
torch.sub(z, x)

tensor([2, 3, 4, 5])

In [16]:
torch.mul(z, x)

tensor([ 3, 10, 21, 36])

In [17]:
torch.div(z, x)

tensor([3.0000, 2.5000, 2.3333, 2.2500])

In [18]:
a = torch.tensor(y)
print(a)
a.add_(z-x)

tensor([2, 3, 4, 5])


tensor([ 4,  6,  8, 10])

In [19]:
r = torch.rand(4,5)
print(r)
print(r[1,:])
print(r[2,0].item())
r.size()

tensor([[0.5767, 0.3088, 0.4683, 0.6107, 0.7042],
        [0.2034, 0.8364, 0.2035, 0.0315, 0.9281],
        [0.4152, 0.1173, 0.5279, 0.1867, 0.7699],
        [0.3690, 0.7718, 0.1115, 0.5540, 0.1183]])
tensor([0.2034, 0.8364, 0.2035, 0.0315, 0.9281])
0.415224552154541


torch.Size([4, 5])

In [20]:
r = r.view(-1, 2)
print(r)
r.size()

tensor([[0.5767, 0.3088],
        [0.4683, 0.6107],
        [0.7042, 0.2034],
        [0.8364, 0.2035],
        [0.0315, 0.9281],
        [0.4152, 0.1173],
        [0.5279, 0.1867],
        [0.7699, 0.3690],
        [0.7718, 0.1115],
        [0.5540, 0.1183]])


torch.Size([10, 2])

**Conversion from Numpy array to Tensor and vice versa**

In [22]:
import numpy as np

In [23]:
a = torch.zeros(4)
print(a)
b = a.numpy()
print(b)
print(b.dtype)

tensor([0., 0., 0., 0.])
[0. 0. 0. 0.]
float32


In [24]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


**Gradient Calculation with Autograd**

In [54]:
x = torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([-0.6300,  1.0058, -2.7907], requires_grad=True)
tensor([-0.6300,  1.0058, -2.7907])


In [50]:
y=x+2
z=y*y*2
print(y)
print(z)
z= z.mean()
print(z)

tensor([1.6410, 1.8742, 1.4072], grad_fn=<AddBackward0>)
tensor([5.3860, 7.0256, 3.9602], grad_fn=<MulBackward0>)
tensor(5.4573, grad_fn=<MeanBackward0>)


In [52]:
z.backward()
print(x.grad)

tensor([2.1880, 2.4990, 1.8762])


**Dummy Training Example For Calculation of Gradients**

In [64]:
weights =torch.ones(4, requires_grad=True)

for  epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
